### ISSUE TITLE
Demos?

### ISSUE THREAD

**Issue by dirkk0** [kittykatattack/sound.js#2]
Could you provide a demo? Or did I miss it?

Thx,
  Dirk

PS: came here via http://www.html5gamedevs.com/topic/13443-what-to-use-for-sounds-in-pixi/#entry76844

**Comment by kittykatattack** [comment]
The demo is actually the `index.html` file itself:

https://cdn.rawgit.com/kittykatattack/soundForGames/master/index.html

**Comment by dirkk0** [comment]
which is kinda cool, but could be more prominent.
maybe create a TL;DR?
