### ISSUE TITLE
Works in Firefox?

### ISSUE THREAD

**Issue by marcoas** [kittykatattack/sound.js#5]
Hi

The demo sound page, works fine in Chrome ( Windows10 ), but not in Firefox 41

It's a bug or a browser incompatibility ?

**Comment by kittykatattack** [comment]
I know it does with with the current version: 41.0.2 and the nightly 43.0a2.
It may have been a browser bug in an earlier version of Firefox?

The demo page is very basic won't inform you when the sounds have loaded.
It could take more than a few seconds for the sounds with a slow network connection.

Please let me know your testing environment and I will try and figure out what could be wrong :smile:

**Comment by marcoas** [comment]
yes works !
sometimes keys i,j,k,l dont work for me.

**Comment by kittykatattack** [comment]
Cool, thanks for posting the question :)
